language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DEPS="numpy scipy scikit-learn astropy nose matplotlib pymc"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - pip install astroML_addons
  - python setup.py install

before_install:
  # then install python version to test
  # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # miniconda is not always up-to-date with conda.
  - conda update -q conda
  - conda info -a

script:
  - nosetests astroML
